sonar.projectKey=TasteTheThunder_Smart-Traffic-Advisory-System
sonar.organization=tastethethunder

sonar.sources=backend

sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io

sonar.python.version=3.11